import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/ui/Header";
import { CartProvider } from "./../context/CartContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/ui/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-white text-black">
          <CartProvider>
            <Header />
            <main className="max-w-screen-xl mx-auto px-4 ">{children}</main>
            <Footer />
          </CartProvider>
          <Toaster position="top-center" />
        </div>
      </body>
    </html>
  );
}
