GET http://localhost:8080/api/v1/brands
Content-Type: application/json
### create
POST http://localhost:8080/api/v1/brands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODQwMzcwYjgwNjVkYjJmNjVlOTgwMmQiLCJlbWFpbCI6InBoYW10aGFpc2FuZzE3MTBAZ21haWwuY29tIiwiaWF0IjoxNzUwMDc1MzMzLCJleHAiOjE3NTAxNjE3MzN9.CDVgxHOdG64Ysi8-FsjXSCae0FUoOg_1ybbU211tyyo

{
  "name": "Nike",
  "description": "Thương hiệu giày thể thao hàng đầu thế giới"
}
### delete
DELETE http://localhost:8080/api/v1/brands/684c0562320934ab5935098e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODQwMzcwYjgwNjVkYjJmNjVlOTgwMmQiLCJlbWFpbCI6InBoYW10aGFpc2FuZzE3MTBAZ21haWwuY29tIiwiaWF0IjoxNzUwMDc4MDczLCJleHAiOjE3NTAxNjQ0NzN9.YC3PXPTMk2di-YiepLfrnKItNbJ6EECfshnEcMIRvDM