POST http://localhost:8080/api/v1/promotions
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODY2YTk1MzQwZTExZmFjNTQ2OTg3YTIiLCJlbWFpbCI6InBzYW5nODM0OEBnbWFpbC5jb20iLCJpYXQiOjE3NTE3MDA3NjUsImV4cCI6MTc1MTc4NzE2NX0.gPac19MDGI-yrIRQ6gHz8VYlSKGkcnBsVQ7GqAueqPs

{
  "code": "SUMMER5e0erqqe",
  "type": "percent",
  "value": 50,
  "expiredAt": "2025-07-31T23:59:59.000Z"
}

###MAHE2002
GET http://localhost:8080/api/v1/promotions