POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "fullName": "phamthaisang",
  "email": "phamthaisang171s0@gmail.com",
    "password": "123456",
    "phone": "0987654321",
    "role": "admin"
}
### get
GET http://localhost:8080/api/v1/users
### delete user
DELETE http://localhost:8080/api/v1/user/6866a69e875488b6669c1edc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODY2YTYyYTg3NTQ4OGI2NjY5YzFlNzMiLCJlbWFpbCI6InBoYW10aGFpc2FuZzE3MTBAZ21haWwuY29tIiwiaWF0IjoxNzUxNTU3OTE3LCJleHAiOjE3NTE2NDQzMTd9.jPXmrrt4HQ3j38snmUg1Il19HOpuqCQaSKsK0z3GibY

###
PUT http://localhost:8080/api/v1/users/6866a69e875488b6669c1edc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODY2YTYyYTg3NTQ4OGI2NjY5YzFlNzMiLCJlbWFpbCI6InBoYW10aGFpc2FuZzE3MTBAZ21haWwuY29tIiwiaWF0IjoxNzUxNTU3OTE3LCJleHAiOjE3NTE2NDQzMTd9.jPXmrrt4HQ3j38snmUg1Il19HOpuqCQaSKsK0z3GibY

{
  "isActive": "false"
}
###
POST http://localhost:8080/api/v1/users/request-otp
Content-Type: application/json

{
  "fullName": "phamthaisang",
  "email": "phamthaisang1710@gmail.com",
  "phone": "0987654321",
  "password": "123456@",
  "role": "admin"
}
###

POST http://localhost:8080/api/v1/users/verify-otp
Content-Type: application/json

{
  "email": "phamthaisang1710@gmail.com",
  "otp": "319505" 
}
###

/*

// ✅ Gửi OTP tới email để tạo tài khoản
router.post(
  "/users/request-otp",

  usersController.requestOtp
);

// ✅ Xác minh OTP và tạo tài khoản
router.post(
  "/users/verify-otp",

  usersController.verifyOtp
);*/
###
PUT http://localhost:8080/api/v1/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODY1NWM3YWQ3OWQ3ZjE4NGQ2Y2MyOTciLCJlbWFpbCI6InBzYW5nODM0OEBnbWFpbC5jb20iLCJpYXQiOjE3NTE1MjQxMDAsImV4cCI6MTc1MTYxMDUwMH0.lmPYbbEirAMPakow14pEJA9I_IemnMWbQghIle14fP0

{
  "currentPassword": "1234567",
  "newPassword": "12345678!"

}